# Generated by Django 3.2.9 on 2022-01-22 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callserviceapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordenemergencia',
            old_name='location_lat',
            new_name='location_cliente_lat',
        ),
        migrations.RemoveField(
            model_name='ordenemergencia',
            name='location_long',
        ),
        migrations.AddField(
            model_name='ordenemergencia',
            name='location_cliente_long',
            field=models.FloatField(blank=True, default=None),
        ),
        migrations.AddField(
            model_name='ordenemergencia',
            name='rubro_requerido',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='ordengeneral',
            name='pedido_mas_información',
            field=models.TextField(default=''),
        ),
    ]
