# Generated by Django 3.2.9 on 2021-12-04 21:21

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('callserviceapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proveedor',
            name='item',
        ),
        migrations.RemoveField(
            model_name='proveedor',
            name='proveedor_company',
        ),
        migrations.RemoveField(
            model_name='proveedor',
            name='proveedor_independiente',
        ),
        migrations.RemoveField(
            model_name='ordenemergencia',
            name='lista_proveedores',
        ),
        migrations.AddField(
            model_name='ordenemergencia',
            name='client_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='ordenemergencia',
            name='fecha_creacion',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ordenemergencia',
            name='lista_proveedores_empresa',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='callserviceapp.item_company'),
        ),
        migrations.AddField(
            model_name='ordenemergencia',
            name='lista_proveedores_independientes',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='callserviceapp.item'),
        ),
        migrations.AddField(
            model_name='ordenemergencia',
            name='proveedor_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='ordenemergencia',
            name='ticket',
            field=models.IntegerField(blank=True, default=1000),
        ),
        migrations.AddField(
            model_name='ordenemergencia',
            name='tiempo_respuesta_promedio',
            field=models.FloatField(default=1000),
        ),
        migrations.AddField(
            model_name='ordengeneral',
            name='client_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='ordengeneral',
            name='fecha_creacion',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ordengeneral',
            name='proveedor_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='ordengeneral',
            name='rubro',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='callserviceapp.item'),
        ),
        migrations.AddField(
            model_name='ordengeneral',
            name='ticket',
            field=models.IntegerField(blank=True, default=1000),
        ),
        migrations.AddField(
            model_name='ordengeneral',
            name='tiempo_respuesta_promedio',
            field=models.FloatField(default=1000),
        ),
        migrations.DeleteModel(
            name='order',
        ),
        migrations.DeleteModel(
            name='Proveedor',
        ),
    ]
