# Generated by Django 3.2.9 on 2022-01-06 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callserviceapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordengeneral',
            old_name='resena',
            new_name='resena_al_cliente',
        ),
        migrations.AddField(
            model_name='client',
            name='cantidad_ordenes_canceladas',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='client',
            name='cantidad_ordenes_realizadas',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='company',
            name='cantidad_ordenes_realizadas',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='company',
            name='cantidad_ordenes_rechazadas',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ordengeneral',
            name='resena_al_proveedor',
            field=models.TextField(blank=True, default=None),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='cantidad_ordenes_realizadas',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='cantidad_ordenes_rechazadas',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ordengeneral',
            name='status',
            field=models.CharField(choices=[('ENV', 'ENVIADA'), ('REC', 'RECIBIDA'), ('ABI', 'ABIERTA'), ('PEI', 'PEDIDO INFORMACION'), ('PRE', 'PRESUPUESTADA'), ('ACE', 'ACEPTADA'), ('EVI', 'EN VIAJE'), ('ENS', 'EN SITIO'), ('RED', 'REALIZADA'), ('CAN', 'CANCELADA'), ('REX', 'RECHAZADA')], default='SO', max_length=3),
        ),
    ]
