# Generated by Django 3.2.9 on 2022-01-28 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callserviceapp', '0002_auto_20220121_2108'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chat',
            old_name='cliente',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='proveedor',
        ),
        migrations.AddField(
            model_name='chat',
            name='ticket',
            field=models.IntegerField(blank=True, default=1000),
        ),
        migrations.AlterField(
            model_name='chat',
            name='day',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='chat',
            name='time',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
