# Generated by Django 3.2.9 on 2022-01-07 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callserviceapp', '0002_auto_20220106_1103'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordengeneral',
            name='califico_el_cliente',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ordengeneral',
            name='califico_el_proveedor',
            field=models.BooleanField(default=False),
        ),
    ]
