# Generated by Django 3.2.9 on 2022-01-07 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callserviceapp', '0003_auto_20220107_1128'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenemergencia',
            name='califico_el_cliente',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ordenemergencia',
            name='califico_el_proveedor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ordenemergencia',
            name='resena_al_cliente',
            field=models.TextField(blank=True, default=None),
        ),
        migrations.AddField(
            model_name='ordenemergencia',
            name='resena_al_proveedor',
            field=models.TextField(blank=True, default=None),
        ),
    ]
