# Generated by Django 3.2.9 on 2022-01-30 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callserviceapp', '0004_auto_20220130_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='day',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chat',
            name='time',
            field=models.TextField(blank=True, null=True),
        ),
    ]
