# Generated by Django 3.2.9 on 2022-04-15 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('callserviceapp', '0007_auto_20220220_1045'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordenemergencia',
            old_name='rubro_requerido',
            new_name='rubro',
        ),
        migrations.RemoveField(
            model_name='ordenemergencia',
            name='tiempo_respuesta_promedio',
        ),
    ]
