# Generated by Django 2.2.12 on 2022-05-21 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callserviceapp', '0008_auto_20220415_1005'),
    ]

    operations = [
        migrations.CreateModel(
            name='ordenEmergenciaLista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket', models.IntegerField(blank=True, default=1000)),
                ('proveedor_email', models.EmailField(blank=True, max_length=254)),
                ('status', models.CharField(choices=[('CE', 'CORREO ENVIADO'), ('CR', 'CORREO RECIBIDO'), ('OA', 'ORDEN ACEPTADA'), ('OR', 'ORDEN RECHAZADA'), ('OD', 'ORDEN DESACTIVADA')], default='SO', max_length=3)),
            ],
        ),
        migrations.RemoveField(
            model_name='ordenemergencia',
            name='lista_proveedores',
        ),
    ]
