# Generated by Django 3.2.13 on 2022-06-05 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callserviceapp', '0009_auto_20220521_1159'),
    ]

    operations = [
        migrations.DeleteModel(
            name='listraProveedoresOrdenEmergencia',
        ),
        migrations.RemoveField(
            model_name='ordenemergencia',
            name='tituloPedido',
        ),
        migrations.AlterField(
            model_name='ordenemergencia',
            name='status',
            field=models.CharField(choices=[('ENV', 'ENVIADA'), ('ACE', 'ACEPTADA'), ('EVI', 'EN VIAJE'), ('ENS', 'EN SITIO'), ('RED', 'REALIZADA'), ('CAN', 'CANCELADA'), ('REX', 'RECHAZADA')], default='SO', max_length=3),
        ),
    ]
