# Generated by Django 3.2.13 on 2022-07-16 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callserviceapp', '0011_alter_ordengeneral_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordengeneral',
            name='day',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='ordengeneral',
            name='time',
            field=models.TextField(default=''),
        ),
    ]
