# Generated by Django 3.2.13 on 2022-07-17 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callserviceapp', '0012_auto_20220716_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordengeneral',
            name='day',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='ordengeneral',
            name='time',
            field=models.TextField(blank=True, default=''),
        ),
    ]
