# Generated by Django 3.2.13 on 2022-07-30 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callserviceapp', '0013_auto_20220717_2328'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenemergencialista',
            name='rubro',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='ordenemergencia',
            name='status',
            field=models.CharField(choices=[('ENV', 'ENVIADA'), ('ACE', 'ACEPTADA'), ('EVI', 'EN VIAJE'), ('ENS', 'EN SITIO'), ('RED', 'REALIZADA'), ('CAN', 'CANCELADA'), ('REX', 'RECHAZADA')], default='ENV', max_length=3),
        ),
    ]
