# Generated by Django 3.2.13 on 2022-09-05 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callserviceapp', '0014_auto_20220730_2135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordenemergencialista',
            name='status',
            field=models.CharField(choices=[('CE', 'CORREO ENVIADO'), ('OA', 'ORDEN ACEPTADA')], default='SO', max_length=3),
        ),
    ]
