# Generated by Django 3.2.13 on 2022-10-08 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callserviceapp', '0015_alter_ordenemergencialista_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='email_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='company',
            name='email_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='email_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
