# Generated by Django 3.2.16 on 2022-10-16 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('callserviceapp', '0016_auto_20221008_0130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordengeneral',
            name='rubro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='callserviceapp.item'),
        ),
    ]
