# Generated by Django 3.2.16 on 2023-01-01 21:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('callserviceapp', '0017_alter_ordengeneral_rubro'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_type', models.IntegerField(blank=True, default=1)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('last_name', models.CharField(blank=True, max_length=200)),
                ('picture', models.ImageField(blank=True, upload_to='media/')),
                ('qualification', models.IntegerField(default=0)),
                ('cantidad_ordenes_realizadas', models.IntegerField(default=0)),
                ('cantidad_ordenes_canceladas', models.IntegerField(default=0)),
                ('posicion_lat', models.FloatField(default=None)),
                ('posicion_long', models.FloatField(default=None)),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='validation_token',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('val_token', models.IntegerField(default=0)),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='client',
        ),
        migrations.RemoveField(
            model_name='item_company',
            name='provider',
        ),
        migrations.RemoveField(
            model_name='campañapublicidad',
            name='company',
        ),
        migrations.RemoveField(
            model_name='campañapublicidad',
            name='serviceProvider',
        ),
        migrations.RemoveField(
            model_name='item',
            name='posicion_lat',
        ),
        migrations.RemoveField(
            model_name='item',
            name='posicion_long',
        ),
        migrations.RemoveField(
            model_name='item',
            name='provider',
        ),
        migrations.RemoveField(
            model_name='ordengeneral',
            name='rubro_company',
        ),
        migrations.AddField(
            model_name='campañapublicidad',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='item',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='item',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.DeleteModel(
            name='company',
        ),
        migrations.DeleteModel(
            name='item_company',
        ),
        migrations.DeleteModel(
            name='serviceProvider',
        ),
    ]
