# Generated by Django 3.2.16 on 2023-01-01 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callserviceapp', '0018_auto_20230101_2129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_data',
            name='posicion_lat',
            field=models.FloatField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='user_data',
            name='posicion_long',
            field=models.FloatField(blank=True, default=None),
        ),
    ]
